[package]
name = "trackball"
version = "0.2.2"
authors = ["Rouven Spreckels <rs@qu1x.dev>"]
edition = "2018"
description = "Virtual Trackball Orbiting via the Exponential Map"
documentation = "https://doc.qu1x.dev/trackball"
repository = "https://github.com/qu1x/trackball"
build = "build.rs"
readme = "README.md"
license = "BSD-3-Clause"
keywords = [
	"virtual-trackball",
	"exponential-map",
	"quaternion",
	"arcball",
	"camera",
]
categories = [
	"graphics",
]
include = [
	"src/**/*.rs",
	"c11/src/**/*.[hc]",
	"build.rs",
	"Cargo.toml",
	"README.md",
	"RELEASES.md",
	"LICENSE.md",
]

[badges]
travis-ci = { repository = "qu1x/trackball" }

[dependencies]
nalgebra = "0.25"

[build-dependencies]
cc = { version = "1", optional = true }
